server:
  port: 9193
spring:
  application:
    name: VISOR-EXAMS-SERVICE
    #visor-master-services
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
#  datasource:
#    url: jdbc:oracle:thin:@164.52.212.83:1522/orcl.ssdcloudindia.net
#    username: accelerate
#    password: password


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      #defaultZone: http://164.52.202.187:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#   hostname: localhost
